version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cara-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cara_db
      POSTGRES_USER: cara_user
      POSTGRES_PASSWORD: qwer1234
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
