spring:
  application:
    name: cara

  datasource:
    url: jdbc:postgresql://210.109.54.109:5432/cara_db
    username: cara_user
    password: qwer1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}

  kakao:
    client:
      client-id: 7c13edee67bab4b026ddc1256ec88eeb
      client-secret: ""
      redirect-uri: http://localhost:8080/v1/oauth/kakao/callback

  jwt:
    secret: VeryLongRandomSecretKeyForHMACSHA256Signing
    expirationMillis: 1209600000   # 14일(2주)를 밀리초로 환산 (14 * 24 * 60 * 60 * 1000)

# application.yml (공통)
app:
  security:
    enabled: true    # 기본은 시큐리티 활성화

---
# src/test/resources/application.yml (테스트 전용)
app:
  security:
    enabled: false   # 테스트 돌릴 땐 시큐리티 비활성화
