spring:
  application:
    name: cara

  datasource:
    url: jdbc:postgresql://localhost:5432/cara_db
    username: cara_user
    password: qwer1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}

  kakao:
    client:
      client-id: 7c13edee67bab4b026ddc1256ec88eeb
      client-secret: ""
      redirect-uri: http://localhost:8080/oauth/kakao/callback

  jwt:
    secret: VeryLongRandomSecretKeyForHMACSHA256Signing
    expirationMillis: 1209600000   # 14일(2주)를 밀리초로 환산 (14 * 24 * 60 * 60 * 1000)
